#!/bin/sh
#  $Id$

#  Copyright 2006 Eduardo Sztokbant <du@du.eti.br>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

shalbumrec_version="beta"
shalbumrec_revision_date='$Date::             $'
shalbumrec_revision="shalbumrec $shalbumrec_version - http://sourceforge.net/projects/shalbum - $shalbumrec_revision_date"

shalbum="/home/eduardo/bin/shalbum"  # path of shalbum script
dirname="master_album"               # dir name for master album
global_title="My Albums"             # title for master album

table_width="800"                    # width of HTML tables
th_res="150"                         # thumbnail resolution
n_columns="3"                        # number of table columns

author="Eduardo Sztokbant"           # site author's name
e_mail='du@du.eti.br'                # site author's e-mail
support_shalbum="yes"                # print link to shalbum site
w3c_ok_banner="yes"                  # print "W3C HTML 4.01 compliant" banner

# HTML layout
color_text="#ffffff"
color_bgcolor="#000000"
color_link="#ffffff"
color_vlink="#888888"
color_alink="#ff0000"
font_face="Arial, Helvetica"

add_credits_footer()
{
    if  [ "$author" != "" ] ||
	[ "$support_shalbum" = "yes" ] ||
	[ "$w3c_ok_banner" = "yes" ]; then
	
	echo "<!-- credits begin -->" >> $1
	echo '<table width="'$table_width'"><tr>' >> $1

	echo '<td width="50%" align="left" valign="top">' >> $1
        # support shalbum!
	if [ "$support_shalbum" = "yes" ]; then
	    echo "<p><font size='1' face='${font_face}'><b>page created with <a href='http://sourceforge.net/projects/shalbum' target='shalbum'><u>shalbum</u></a></b></font></p>" >> $1
	fi
	
        # W3C HTML 4.01 compliant banner
	if [ "$w3c_ok_banner" = "yes" ]; then
	    echo '<p><a href="http://validator.w3.org/check?uri=referer"><img border="0" src="http://www.w3.org/Icons/valid-html401" alt="Valid HTML 4.01 Transitional" height="31" width="88"></a></p>' >> $1
	fi
	echo "</td>" >> $1
	
	echo '<td width="50%" align="right" valign="top">' >> $1
        # Author
	if [ "$author" != "" ]; then
	    echo "<p><font size='1' face='${font_face}'><b>$credits_str $author</b></font><br />" >> $1
	    echo "<a href='mailto:$e_mail'><font size='1' face='${font_face}'><b>$e_mail</b></font></a></p>" >> $1
	fi
	
	echo '</tr></table>' >> $1
	echo "<!-- credits end -->" >> $1
    fi
}

IFS='
'

dot_dirname=".${dirname}"
dot_dirname_bak="${dot_dirname}.bak"
mkdir -p "${dot_dirname}"

if [ -e "${dirname}" ]; then
    if [ -e "${dot_dirname_bak}" ]; then
	echo -n "Cleaning up previous backup directory..."
	rm -rf "${dot_dirname_bak}"
	echo "done!"
    fi
    mv "${dirname}" "${dot_dirname_bak}"
fi

# create albums
for dir in `ls`; do
    if [ -d "$dir" ]; then
	echo "- Entering '$dir' directory..."

	cd "$dir"
   	${shalbum}
   	cd - 1>/dev/null
	mkdir -p "${dot_dirname}/$dir"
   	mv "$dir/album/"* "${dot_dirname}/$dir"
	rmdir "$dir/album"
    fi
done

# create thumbnails and master index.html file
cd "${dot_dirname}"

echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">' > index.html
echo "<html>" >> index.html
echo "<head>" >> index.html
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">" >> index.html
echo "<style TYPE=\"text/css\"> A:link, A:visited { text-decoration: none; } </style>" >> index.html
echo "<title>${global_title}</title>" >> index.html
echo "</head>" >> index.html
echo "<body text='$color_text' bgcolor='$color_bgcolor' link='$color_link' vlink='$color_vlink' alink='$color_alink'><center>" >> index.html
echo "<table width='$table_width'><tr><td>" >> index.html
echo "<font size='5' face='${font_face}'><b>${global_title}</b></font>" >> index.html
echo "</td></tr></table>" >> index.html
echo "<table width='$table_width'>" >> index.html

col_percentage=$((100/$n_columns))
col_counter="0"

for dir in `ls`; do
    if [ -d "$dir" ]; then
	cd "$dir"
	FIRST="`grep img index.html | head -1 | cut -d \\\" -f 6`"
	TITLE="`grep '<!-- shalbumrec:title' index.html | cut -d ¬ -f 2`"
	DATE="`grep '<!-- shalbumrec:date' index.html | cut -d ¬ -f 2`"

	echo "Generating thumbnail for '$dir'"
	convert "vga/vga_${FIRST}" -resize ${th_res}x${th_res} ../th_"${dir}".jpg

	if [ $col_counter -eq 0 ]; then
	    echo "<tr>" >> ../index.html
	fi

	echo "<td width='${col_percentage}%'><table><tr><td width='${th_res}' valign='top'><a href='$dir/index.html'><img border='0' alt='$dir' src='thumbnails/th_${dir}.jpg'></a></td><td valign='top' align='left'><a href='$dir/index.html'><font size='3' face='${font_face}'><b>${TITLE}</b></font></a><br /><font size='2' face='${font_face}'>${DATE}</font></td></tr></table></td>" >> ../index.html

	col_counter="$(($col_counter+1))"
	if [ $col_counter -eq $n_columns ]; then
	    echo "</tr>" >> ../index.html
	    col_counter="0"
	fi

	cd - 1>/dev/null
    fi
done

if [ ! $col_counter -eq 0 ]; then
    echo "</tr>" >> index.html
fi

echo "</table>" >> index.html

add_credits_footer index.html

echo "</center></body></html>" >> index.html
echo "<!-- created with $shalbumrec_revision -->" >> index.html

mkdir -p "thumbnails"
mv th_*.jpg "thumbnails"
cd ..
mkdir "${dirname}"
mv "${dot_dirname}/"* "${dirname}"
rmdir "${dot_dirname}"

echo "Done!"
